[package]
name = "routes"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
reqwest = { version = "0.12.15", features = ["json"] }
serde = "1.0.218"
serde_json = "1.0.139"
